// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBry2cNkj9Awiy8J9MUZwoOTYlKbEkk8bY',
    appId: '1:100273481671:web:74941f2e6a754c6f839be2',
    messagingSenderId: '100273481671',
    projectId: 'alkohut-5bf97',
    authDomain: 'alkohut-5bf97.firebaseapp.com',
    storageBucket: 'alkohut-5bf97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Rwdo1aZoU05bssybSHZKT5_truWe4D4',
    appId: '1:100273481671:android:1247eaf290e41939839be2',
    messagingSenderId: '100273481671',
    projectId: 'alkohut-5bf97',
    storageBucket: 'alkohut-5bf97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoX8O2atc0OLxdnx3ILQdLheoC2nM6ONI',
    appId: '1:100273481671:ios:25e8d611b0978264839be2',
    messagingSenderId: '100273481671',
    projectId: 'alkohut-5bf97',
    storageBucket: 'alkohut-5bf97.firebasestorage.app',
    iosBundleId: 'com.example.chupachap',
  );
}
