// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0S5ekJlsU9aLhx4GTs3bcdDk0zMZn_U',
    appId: '1:1027765291967:web:acf75f58489b8ca87d6f0a',
    messagingSenderId: '1027765291967',
    projectId: 'chupachap-e861a',
    authDomain: 'chupachap-e861a.firebaseapp.com',
    storageBucket: 'chupachap-e861a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fO5uMctjAwGektoGriopf6NtBTKrxoY',
    appId: '1:1027765291967:android:934900f6f511950b7d6f0a',
    messagingSenderId: '1027765291967',
    projectId: 'chupachap-e861a',
    storageBucket: 'chupachap-e861a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7CNeUE7deCvd-mEn1qymazsjiliaeyo',
    appId: '1:1027765291967:ios:e2d0c5ebcdb115f47d6f0a',
    messagingSenderId: '1027765291967',
    projectId: 'chupachap-e861a',
    storageBucket: 'chupachap-e861a.firebasestorage.app',
    iosBundleId: 'com.example.chupachap',
  );
}
